name: Publish Python Package

on:
  push:
    tags: ["**"]
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.inspect_package.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.4"
          python-version: "3.12"
          enable-cache: true

      - name: Build package
        run: uv build --all-packages

      - name: Inspect package version
        id: inspect_package
        run: |
          version=$(uvx hatchling version)
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: package-distributions
          path: dist/

  pypi-publish:
    if: github.event_name == 'push' && github.ref == 'refs/tags/v*'
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    environment:
      name: pypi
      url: https://pypi.org/project/siteforge/${{ needs.build.outputs.version }}

    steps:
    - name: Download package
      uses: actions/download-artifact@v4
      with:
        name: package-distributions
        path: dist/

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true

  pypi-test-publish:
    if: github.event_name == 'push' && github.ref != 'refs/tags/v*'
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    environment:
      name: pypi-test
      url: https://test.pypi.org/project/siteforge/${{ needs.build.outputs.version }}

    steps:
    - name: Download package
      uses: actions/download-artifact@v4
      with:
        name: package-distributions

# TODO: Add pypi-test-publish job to publish to test.pypi.org.

